### ISSUE TITLE
ideia

### ISSUE THREAD

**Issue by ghost** [hesronsilva/FinancialLife#1]

**Comment by hesronsilva** [comment]
Ola gostaria sim, meu interesse e dar continuidade nele para se torna de repente um app de controle financeiro aberto ao publico
________________________________

**Comment by hesronsilva** [comment]
Se quiser me chama no WhatsApp 31988899406

**Comment by hesronsilva** [comment]
Se quiser me chamar no whats 31988899406

________________________________
